{{- if not .Values.bootstrap.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "octofhir.fullname" . }}-secret
  labels:
    {{- include "octofhir.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.bootstrap.adminUser.password }}
  admin-password: {{ .Values.bootstrap.adminUser.password | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.bootstrap.backendClient.clientSecret }}
  backend-client-secret: {{ .Values.bootstrap.backendClient.clientSecret | b64enc | quote }}
  {{- else }}
  backend-client-secret: {{ randAlphaNum 48 | b64enc | quote }}
  {{- end }}
  {{- if and (not .Values.postgresql.enabled) .Values.externalPostgresql.password (not .Values.externalPostgresql.existingSecret) }}
  postgresql-password: {{ .Values.externalPostgresql.password | b64enc | quote }}
  {{- end }}
{{- end }}
